### ISSUE TITLE
[cloudevents] Controller Integration Roadmap

### ISSUE THREAD

**Issue by waveywaves** [tektoncd/experimental#830]
### Feature request

This issue tracks the requirements for the cloudevents controller to be in a position to be integrated with Tekton Pipeline as a standalone controller. 

- [ ] Relay cloudevents from one controller to the others (to triggers, results etc.)
- [ ] Already supported Tekton Pipeline Cloudevents
- [ ] CdEvents Format support
- [ ] TEP for replacing this controller with Tekton Pipeline cloudevents functionality
